### ISSUE TITLE
issue after upgrade - update fails

### ISSUE THREAD

**Issue by Zorkny** [TekniskSupport/home-assistant-skola24-to-ical#11]
ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.ical_skola fails

have not changed anything but could be related to this?

2022-05-08 09:53:14 WARNING (MainThread) [homeassistant.components.calendar] CalendarEventDevice is deprecated, modify ICalCalendarEventDevice to extend CalendarEntity

Log:

2022-05-08 09:59:14 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.ical_skola fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
    raise exc
  File "/config/custom_components/ical/calendar.py", line 73, in async_update
    await self.ical_events.update()
  File "/config/custom_components/ical/__init__.py", line 130, in update
    event_list = icalendar.Calendar.from_ical(text.replace("\x00", ""))
  File "/usr/local/lib/python3.9/site-packages/icalendar/cal.py", line 399, in from_ical
    raise ValueError('Found no components where '
ValueError: Found no components where exactly one is required: 'BEGIN:VCALENDAR\nVERSION:2.0\nCALSCALE:GREGORIAN\nBEGIN:VEVENT\nSUMMARY:SVESVE02\nDTSTART;TZID=Europe/Berlin:20220419T131000\nDTEND;TZID=Europe/Berlin:20220419T143000\nLOCATION:225\nDESCRIPTION:SVESVE02\nSTATUS:CONFIRMED\nSEQUENCE:3\nEND:VEVENT\nBEGIN:VEVENT\nSUMMARY:MATMAT04\nDTSTART;TZID=Europe/Berlin:20220419T111000\nDTEND;TZID=Europe/Berlin:20220419T122500\nLOCATION:044\nDESCRIPTION:MATMAT04\nSTATUS:CONFIRMED\nSEQUENCE:3\nEND:VEVENT\nBEGIN:VEVENT\nSUMMARY:Lunch\nDTSTART;TZID=Europe/Berlin:20220419T123500\nDTEND;TZID=Europe/Berlin:20220419T125500\nLOCATION:\nDESCRIPTION:Lunch\nSTATUS:CONFIRMED\nSEQUENCE:3\nEND:VEVENT\nBEGIN:VEVENT\nSUMMARY:BIOBIO02\nDTSTART;TZID=Europe/Berlin:20220419T100000\nDTEND;TZID=Europe/Berlin:20220419T110000\nLOCATION:405\nDESCRIPTION:BIOBIO02\nSTATUS:CONFIRMED\nSEQUENCE:3\nEND:VEVENT\nBEGIN:VEVENT\nSUMMARY:KEMKEM02\nDTSTART;TZID=Europe/Berlin:20220419T144000\nDTEND;TZID=Europe/Berlin:20220419T154000\nLOCATION:413\nDESCRIPTION:KEMKEM02\nSTATUS:CONFIRMED\nSEQUENCE:3\nEND:VEVENT\nBEGIN:VEVENT\nSUMMARY:ENGENG06\nDTSTART;TZID=Europe/Berlin:20220419T083000\nDTEND;TZID=Europe/Berlin:20220419T095000\n'
2022-05-08 09:59:18 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 740, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 520, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 680, in _async_write_ha_state

**Comment by TekniskSupport** [comment]
Hi Zorkny, I think this issue is with the ical-integration,

Found this issue on the matter;
https://github.com/tybritten/ical-sensor-homeassistant/issues/91
